server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mt
    username: postgres
    password: postgres
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none